---
name: Bug report
description: File a bug/issue
title: "[Bug]: "
labels: ["bug"]

body:
- type: markdown
  attributes:
    value: '# Reminder'
- type: markdown
  attributes:
    value: |
            The responses are provided by the **community** and, on a **best effort** basis, by some Belledonne Communications SARL engineers working on Linphone and its related projects.
            The community means any people all around the world simply willing to participate to the discussions.

            Belledonne Communications SARL **disclaims any WARRANTY** that the content posted on github issues or mailing lists is technically correct.
            Responses from Belledonne Communications SARL engineers shall be considered as individual contributions and shall not be seen as Belledonne Communications's official point of view or commitment.

            The Github issue tracker must be seen as a place for **collaboration**. Issues submitted should be of general interest, in the goal of improving the software. Consider that a **well documented** issue (with precise reproduction procedure, logs, stack trace if relevant, possibly a corrective patch) has a higher chance to receive interest and feedback from community members and Belledonne Communications' engineers.

            __Issues poorly documented, with no facts, or asking for debugging assistance for a custom app using Linphone's libraries, or for a modified version of Linphone are unlikely to receive any kind of response.__

            People using Linphone or its related projects within the scope of their company job are invited to contact [Belledonne Communications](https://linphone.org/contact#content-bottom3) in order to obtain commercial support.


- type: textarea
  attributes:
    label: |
            Please explain the context (ex: Running with sip.linphone.org/own self-hosted server with [...] SIP server of version [...]) :
    description: |
                  - For which purpose do you use the project ?
                  - With which software/hardware it is integrated ?
    value: |
            A clear and concise description of what the bug is.

- type: textarea
  attributes:
    label: General information
    value: |
            - Device: [e.g. Samsung Note 20 Ultra]
            - OS: [e.g. Android 11]
            - Version of the App [e.g. 4.3.1]
            - Version of the SDK [e.g 4.4.16]
  validations:
    required: true

- type: markdown
  attributes:
    value: |
            **Expected behavior**
            A clear and concise description of what you expected to happen.
            **Please complete the following information**

- type: textarea
  attributes:
    label: To Reproduce
    description: "Steps to reproduce the behavior:"
    value: |
            1. Go to '...'
            2. Click on '....'
            3. Scroll down to '....'
            4. See error
    value: operating system
  validations:
    required: true

- type: textarea
  attributes:
    label: 'SDK logs'
    description: |
                  Enable debug logs in advanced section of the settings, restart the app, reproduce the issue and then go to About page, click on "Send logs" and copy/paste the link here.
  validations:
    required: true

- type: textarea
  attributes:
    label: 'Adb logcat logs'
    description: |
                  In case of a crash of the app, please also provide the stack trace of the crash using adb logcat.
  validations:
    required: true

- type: textarea
  attributes:
    label: 'Screenshots'
    description: |
                  If applicable, add screenshots to help explain your problem.
  validations:
    required: false

- type: textarea
  attributes:
    label: 'Pcap file'
    description: |
                  If applicable, join a pcap file of your issue (done with Wireshark or TCPDump, for example)
  validations:
    required: false

- type: textarea
  attributes:
    label: 'Additional context'
    placeholder: Add any other context about the problem here.
  validations:
    required: false
